//
//  PDFExport.swift
//  LUMEN
//
//  Generates a simple branded PDF summary of the user's ritual data.
//

import UIKit

@MainActor
enum PDFExport {
    static func makeReport(user: UserState, productCount: Int, perfectDays: Int) -> URL? {
        let pageRect = CGRect(x: 0, y: 0, width: 612, height: 792)
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("LUMEN-Report.pdf")

        do {
            try renderer.writePDF(to: url) { ctx in
                ctx.beginPage()
                let gold = UIColor(red: 0.79, green: 0.66, blue: 0.40, alpha: 1)
                let dark = UIColor(red: 0.10, green: 0.10, blue: 0.11, alpha: 1)

                func draw(_ text: String, _ font: UIFont, _ color: UIColor, at point: CGPoint) {
                    text.draw(at: point, withAttributes: [.font: font, .foregroundColor: color])
                }

                draw("LUMEN", UIFont.systemFont(ofSize: 28, weight: .semibold), gold, at: CGPoint(x: 48, y: 56))
                draw("Your Ritual Report", UIFont.systemFont(ofSize: 16), dark, at: CGPoint(x: 48, y: 96))
                draw(Date.now.formatted(date: .long, time: .omitted), UIFont.systemFont(ofSize: 12), .gray, at: CGPoint(x: 48, y: 120))

                let rows: [(String, String)] = [
                    ("Ritual Rank", user.rank.rawValue),
                    ("Total XP", "\(user.xp)"),
                    ("Current streak", "\(user.streak) days"),
                    ("Best streak", "\(user.bestStreak) days"),
                    ("Streak freezes", "\(user.freezes)"),
                    ("Perfect days logged", "\(perfectDays)"),
                    ("Products on shelf", "\(productCount)"),
                    ("Medals unlocked", "\(user.medalsUnlocked.count) / \(Medal.all.count)"),
                ]

                var y: CGFloat = 180
                for (label, value) in rows {
                    draw(label, UIFont.systemFont(ofSize: 14), .darkGray, at: CGPoint(x: 48, y: y))
                    draw(value, UIFont.systemFont(ofSize: 14, weight: .semibold), dark, at: CGPoint(x: 360, y: y))
                    y += 40
                }

                draw("Generated by LUMEN — your daily self-care ritual.", UIFont.systemFont(ofSize: 11), .gray, at: CGPoint(x: 48, y: 740))
            }
            return url
        } catch {
            return nil
        }
    }
}
